// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-b2Hwtii5YlEZb2pjYF5ZX01jvnVgoC4',
    appId: '1:344536959320:web:f4034b7d5285923cb0fd2d',
    messagingSenderId: '344536959320',
    projectId: 'chat-4f345',
    authDomain: 'chat-4f345.firebaseapp.com',
    storageBucket: 'chat-4f345.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf79sizrcnTibQ-Cd1U1WdN8-QZapdLOs',
    appId: '1:344536959320:android:41f7b9ded8db6736b0fd2d',
    messagingSenderId: '344536959320',
    projectId: 'chat-4f345',
    storageBucket: 'chat-4f345.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnyRHivor0ol00O4NLZSozC8XnYu3-z0g',
    appId: '1:344536959320:ios:d4299f22f1661e1ab0fd2d',
    messagingSenderId: '344536959320',
    projectId: 'chat-4f345',
    storageBucket: 'chat-4f345.appspot.com',
    iosClientId: '344536959320-jn73pdtr8hlqsube0j5li3qj16uulmjk.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnyRHivor0ol00O4NLZSozC8XnYu3-z0g',
    appId: '1:344536959320:ios:2307534ff99fb258b0fd2d',
    messagingSenderId: '344536959320',
    projectId: 'chat-4f345',
    storageBucket: 'chat-4f345.appspot.com',
    iosClientId: '344536959320-ueuaajlgh5qv35c92sivn13g3mu9fia2.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter.RunnerTests',
  );
}
